import React from 'react';
import { Link } from 'react-router-dom';

export default function NotFound() {
  return (
    <div className="min-h-screen bg-gray-900 text-white font-sans flex items-center justify-center p-4">
      <div className="text-center max-w-md">
        <div className="w-24 h-24 bg-gray-800 rounded-full flex items-center justify-center mx-auto mb-8 shadow-xl shadow-purple-500/10">
           <i className="fas fa-ghost text-5xl text-purple-400 animate-bounce"></i>
        </div>
        
        <h1 className="text-6xl font-bold mb-4 bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">404</h1>
        <h2 className="text-2xl font-bold mb-4">Page Not Found</h2>
        <p className="text-gray-400 mb-8">
          Oops! The page you're looking for doesn't exist or has been moved. 
          Maybe it's still being generated by AI?
        </p>
        
        <div className="flex flex-col gap-3">
          <Link 
            to="/" 
            className="w-full gradient-bg py-3 rounded-xl font-bold hover:opacity-90 transition shadow-lg"
          >
            Return Home
          </Link>
          <button 
            onClick={() => window.history.back()}
            className="w-full bg-gray-800 border border-gray-700 py-3 rounded-xl font-medium hover:bg-gray-700 transition"
          >Go Back</button>
        </div>
      </div>
    </div>
  );
}
